### ISSUE TITLE
Change of Ireland VAT rate

### ISSUE THREAD

**Issue by Merkandi** [mpociot/vat-calculator#98]
Ireland has announced a temporary Value Added Tax rate cut from 23% to 21%. The measure will come into place on 1 September 2020 until 28 February 2021.

source: https://www.avalara.com/vatlive/en/vat-news/ireland-cuts-vat-from-23--to-21--till-feb-2021.html

**Comment by Fossil01** [comment]
A lot of countries changed their VAT rates:

https://www.avalara.com/vatlive/en/vat-rates/european-vat-rates.html

**Comment by spaze** [comment]
@Fossil01 

According to https://www.avalara.com/vatlive/en/vat-news/covid-19-vat-rate-changes.html these are the countries that have changed their *standard rates* or *reduced rates*:

Country | Supply | Old rate | New rate | Implementation date | End date
--|--|--|--|--|--
Costa Rica | Standard rate | 13% | 9% | TBC | TBC
Germany | Standard rate | 19% | 16% | 01 Jul 2020 | 31 Dec 2020
Germany | Reduced rate | 7% | 5% | 01 Jul 2020 | 31 Dec 2020
Ireland | Standard rate | 23% | 21% | 01 Sep 2020 | 28 Feb 2021
Jamaica | Standard rate | 16.5% | 15% | 01 Apr 2020 | 31 Mar 2021
Kenya | Standard rate | 16% | 14% | 01 Apr 2020 | -
Mexico | Standard rate | 16% | 10% | TBC | TBC
Saudi Arabia | Standard Rate | 5% | 15% | 01 Jul 2020 | -

From that list, only Germany and Ireland are EU member states. Other changes in other countries are done selectively per industry, for example Hospitality, Restaurants etc.

**Comment by driesvints** [comment]
I'm going to let this one pass by. It's not so long until the end of february anymore and I don't see it feasible to implement it now and then change it back again within a month. Apps would all need to update on exactly the beginning of March. Since this has been in the library all the time since the beginning of the temporary new rate another month isn't too big of a deal.
